apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  namespace: khool-kpl-podqos
  labels:
    hol.khool.net/scope: demo
spec:
  terminationGracePeriodSeconds: 30
  containers:
  - name: logger
    image: kanedafromparis/logversion:2.0
    resources:
      requests:
        cpu: 500m
        memory: "100Mi"
      limits:
        cpu: 500m
        memory: "100Mi"
      