apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
  namespace: khool-kpl-podqos
  labels:
    hol.khool.net/scope: demo
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: logger
    image: kanedafromparis/logversion:2.0
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
      