apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: d-qos-besteffort
  namespace: khool-kpl-podqos
  labels:
    app: d-qos-besteffort
    hol.khool.net/scope: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: d-qos-besteffort
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: d-qos-besteffort
        hol.khool.net/scope: qos-besteffort
    spec:
      containers:
      - image: kanedafromparis/logversion:2.0
        imagePullPolicy: IfNotPresent
        name: logversion
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5

