apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 1
  name: dc-qos-burstable
  namespace: khool-kpl-podqos
  labels:
    app: qos-burstable
    hol.khool.net/scope: demo
spec:
  replicas: 2
  selector:
    app: dc-qos-burstable
    deploymentconfig: dc-qos-burstable
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: dc-qos-burstable
        deploymentconfig: dc-qos-burstable
        hol.khool.net/scope: qos-burstable
    spec:
      containers:
      - image: kanedafromparis/logversion:2.0
        imagePullPolicy: IfNotPresent
        name: logversion
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5

