apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: khool-kpl-resourcequota
  labels:
    hol.khool.net/scope: demo
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: 250Mi
    limits.cpu: "3"
    limits.memory: 1Gi